### ISSUE TITLE
Sample program not working🐛

### ISSUE THREAD

**Issue by aneeskA** [JoeScho/oas2joi#13]
**Describe the bug**

Example given not working. Sample output.

> D:\Work\oas2joi.sample\node_modules\enjoi\index.js:18
>     const validateOptions = Joi.validate(options, optionsSchema);
>                                 ^
> 
> TypeError: Joi.validate is not a function
>     at validate (D:\Work\oas2joi.sample\node_modules\enjoi\index.js:18:33)
>     at Object.exports.schema (D:\Work\oas2joi.sample\node_modules\enjoi\index.js:49:15)
>     at parseSchema (D:\Work\oas2joi.sample\node_modules\oas2joi\index.js:11:16)
>     at Object.keys.forEach.schemaName (D:\Work\oas2joi.sample\node_modules\oas2joi\index.js:20:30)
>     at Array.forEach (<anonymous>)
>     at module.exports.filePath (D:\Work\oas2joi.sample\node_modules\oas2joi\index.js:19:27)
>     at Object.<anonymous> (D:\Work\oas2joi.sample\app.js:31:17)
>     at Module._compile (internal/modules/cjs/loader.js:701:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
>     at Module.load (internal/modules/cjs/loader.js:600:32)

**To Reproduce**
Steps to reproduce the behavior.

```
const oas2joi = require('oas2joi');
const Joi = require('@hapi/joi');

const schemas = oas2joi('./open-api.yml');

console.log(schemas)

const someObject = {
  foo: 'bar'
};

const { error } = Joi.validate(someObject, schemas.someObject);
```

**Expected behavior**

execution without errors

**Screenshots**

**Additional context**

**Comment by JoeScho** [comment]
Thanks for pointing this out. It looks like this is due to a bug in `enjoi`. https://github.com/tlivings/enjoi/issues/79

I'll leave this issue open as I'll need to version bump enjoi when fixed

**Comment by JoeScho** [comment]
Depends on https://github.com/tlivings/enjoi/pull/84
